### ISSUE TITLE
Please guide how to use your repo. 

### ISSUE THREAD

**Issue by JafferWilson** [wisutsak/iqapi#1]
Share one sample of the config.json please

**Comment by wisutsak** [comment]
https://github.com/n1nj4z33/iqoptionbot

ในวันที่ พ. 27 มิ.ย. 2018 เวลา 16:00 Jaffer Wilson <notifications@github.com>
เขียนว่า:

**Comment by wisutsak** [comment]
{
    "connection_settings": {
        "hostname": "iqoption.com",
        "password": "password",
        "username": "username"
    },
    "trade_settings": {
        "actives": [
            "EURUSD-OTC",
            "EURUSD"
        ],
        "patterns": [
            "TEST",
            "TBH"
        ]
    }
}



ในวันที่ พ. 27 มิ.ย. 2018 เวลา 16:44 wisutsak jaisue <wisutsak.ad@gmail.com>
เขียนว่า:
